<?php
DEFINE("DEBUG", false); //true or false

DEFINE("MYSQL_HOST", "localhost");
DEFINE("MYSQL_PORT", 3306);
DEFINE("MYSQL_USERNAME", "");
DEFINE("MYSQL_PASSWORD", "");
DEFINE("MYSQL_DATABASE", "");

DEFINE("SF_CLIENT_ID", "");
DEFINE("SF_CLIENT_SECRET", "");
DEFINE("SF_USERNAME", "");
DEFINE("SF_PASSWORD", "");
DEFINE("SF_SECURITY", "");

